# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test js cypresss

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./js/cypress

    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    strategy:
      matrix:
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/releases/
        node-version: [16.x]
        # as many jobs as you want, but less than numbers of tests
        # e.g., shard: [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
        shard: [1,2,3,4]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./js/cypress
        cache: 'npm'
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: install deps
      run: npm i
    - name: find test files to be run
      run: echo "SHARD_FILES=$(find cypress/e2e -type f -name "*.js" | grep -v helper | sed -n '${{matrix.shard}}~${{strategy.job-total}}p' | tr '\n' ' ')" >> $GITHUB_ENV
    - name: run tests
      run: npm run test -- --spec ${{env.SHARD_FILES}}
